# Generated by Django 4.0.1 on 2022-02-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stremstv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='video',
            field=models.BooleanField(default=False),
        ),
    ]
