# Generated by Django 4.0.1 on 2022-02-07 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stremstv', '0003_referral_referraluser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Referral',
        ),
        migrations.DeleteModel(
            name='ReferralUser',
        ),
    ]
