# Generated by Django 4.0.1 on 2022-02-07 18:54

from decimal import Decimal
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=30)),
                ('site', models.URLField()),
                ('note', models.TextField(blank=True, null=True)),
                ('token', models.UUIDField(default=uuid.UUID('e825d27e-891c-4235-b0ce-caedd6e5214f'))),
                ('downloads', models.IntegerField(default=0)),
                ('unique_users', models.IntegerField(default=0)),
                ('total_requests', models.IntegerField(default=0)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
            ],
            options={
                'verbose_name': 'partner',
                'verbose_name_plural': 'partners',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ReferralUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.BigIntegerField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(max_length=255)),
                ('download', models.BooleanField(default=False)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
            ],
        ),
    ]
