# Generated by Django 4.0.1 on 2022-02-08 17:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='downloads',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='total_requests',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='unique_users',
        ),
        migrations.RemoveField(
            model_name='referraluser',
            name='token',
        ),
        migrations.AddField(
            model_name='referraluser',
            name='ref_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='token',
            field=models.UUIDField(default=uuid.UUID('20b314c1-12e0-49a5-bae2-0c042bd7ed72')),
        ),
    ]
