# Generated by Django 4.0.1 on 2022-02-08 18:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_remove_referral_downloads_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='token',
            field=models.UUIDField(default=uuid.UUID('c8567a45-2d53-48af-ac2e-aff62355fe7c')),
        ),
    ]
