# Generated by Django 4.0.1 on 2022-02-09 16:55

from django.db import migrations, models
import tinymce.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0003_alter_referral_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.IntegerField(default=1)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AlterField(
            model_name='referral',
            name='token',
            field=models.UUIDField(default=uuid.UUID('bbe4ee7d-abf1-4a21-905e-460251bd284b')),
        ),
    ]
